config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
  resources :logins, :only => [:new, :create, :destroy]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :pets
  validates :password, :length => { :minimum => 8 }, :if => :password
  validates :email, :presence => true, :uniqueness => true
  before_save :downcase_fields

  def downcase_fields
     self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.where(:email => params[:email].downcase).first
    if user && user.authenticate(params[:password])
      flash[:notice] = "You have been logged in"
      session[:current_user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:notice] = "There was a problem logging in, please try again"
      render :new
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    flash[:notice] = "Thanks for visiting, come back soon"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to user_path(@user)
    else
      render new
    end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params_update)
     flash[:notice] = "User info successfully updated!"
     redirect_to user_path(@user)
   else
     render :show
   end
 end

private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def user_params_update
    params.require(:user).permit(:email, :name, :about, :profile_pic, :skills, :zip, :likes_to)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>It Takes a Village</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItTakesAVillage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:current_user_id] %>
    <nav>
      <%= link_to "Home", root_url %>
      <%= link_to "Log Out", login_path(0),
                  :data => {:method => "delete"}%>
                </nav>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Login", new_login_path %>
    <% end %>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/logins/new.html.erb
<%= form_tag("/logins", method: "post") do %>
  <%= label_tag(:email)%>
  <%= text_field_tag(:email) %>
  <%= label_tag (:password) %>
  <%= password_field_tag (:password) %>
  <%= submit_tag ("Login"), :id => "signin" %>
<% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :about %>
  <%= f.text_field :about %>
  <%= f.label :profile_pic %>
  <%= f.text_field :profile_pic %>
  <%= f.label :skills %>
  <%= f.text_field :skills %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :likes_to %>
  <%= f.text_field :likes_to %>
  <%= f.submit  %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h3>Welcome!</h3>

<%= render "form" %>